//create an array of JSON Objects containing the players' details
const players = [
    {
        name: "David Raya",
        team: "Arsenal",
        nationality: "Spain",
        jerseyNumber: 22,
        age: 28,
        imageUrl: "images/jersey1.jpg",
    },
    {
        name: "Ben White",
        team: "Arsenal",
        nationality: "England",
        jerseyNumber: 18,
        age: 26,
        imageUrl: "images/jersey.jpeg",
    },
    {
        name: "William Saliba",
        team: "Arsenal",
        nationality: "France",
        jerseyNumber: 2,
        age: 23,
        imageUrl: "images/jersey.jpeg",
    },
    {
        name: "Gabriel Magalhaes",
        team: "Arsenal",
        nationality: "Brazil",
        jerseyNumber: 6,
        age: 25,
        imageUrl: "images/jersey.jpeg",
    },

    {
        name: "Oleksandr Zinchenko",
        team: "Arsenal",
        nationality: "Ukraine",
        jerseyNumber: 35,
        age: 26,
        imageUrl: "images/jersey.jpeg",
    },
    {
        name: "Martin Odegaard",
        team: "Arsenal",
        nationality: "Norway",
        jerseyNumber: 8,
        age: 24,
        imageUrl: "images/jersey.jpeg",
    },
    {
        name: "Declan Rice",
        team: "Arsenal",
        nationality: "England",
        jerseyNumber: 41,
        age: 24,
        imageUrl: "images/jersey.jpeg",
    },
    {
        name: "Leandro Trossard",
        team: "Arsenal",
        nationality: "Belgium",
        jerseyNumber: 19,
        age: 29,
        imageUrl: "images/jersey.jpeg",
    },
    {
        name: "Bukayo Saka",
        team: "Arsenal",
        nationality: "England",
        jerseyNumber: 7,
        age: 22,
        imageUrl: "images/jersey.jpeg",
    },
    {
        name: "Gabriel Jesus",
        team: "Arsenal",
        nationality: "Brazil",
        jerseyNumber: 9,
        age: 26,
        imageUrl: "images/jersey.jpeg",
    },
    {
        name: "Gabriel Martinelli",
        team: "Arsenal",
        nationality: "Brazil",
        jerseyNumber: 11,
        age: 22,
        imageUrl: "images/jersey.jpeg",
    },
    ];
    
    export default players;